/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface User {
  first_name: string;
  last_name: string;
  email: string;
  channels: Channel[];
  custodian?: Custodian;
  banner?: Banner;
  [k: string]: unknown;
}
export interface Channel {
  channel_identifier: string;
  [k: string]: unknown;
}
export interface Custodian {
  provider: string;
  [k: string]: unknown;
}
export interface Banner {
  url: string;
  [k: string]: unknown;
}
